using System.Globalization;

namespace PrinterTool;

public static class Loc
{
    public static string Lang { get; private set; } = "en";

    public static readonly (string Code, string Native)[] Languages =
    {
        ("en", "English"), ("de", "Deutsch"), ("it", "Italiano"), ("fr", "Français"),
        ("pt", "Português"), ("es", "Español"), ("zh", "中文"), ("ja", "日本語"),
        ("da", "Dansk"), ("nl", "Nederlands"), ("sv", "Svenska"),
        ("tr", "Türkçe"), ("ar", "العربية"), ("ko", "한국어"),
    };

    public static void Init(string? saved)
    {
        string sys = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        string pick = saved ?? sys;
        Lang = Languages.Any(l => l.Code == pick) ? pick : "en";
    }

    public static void Set(string code) => Lang = code;

    public static string T(string key) =>
        Table.TryGetValue(key, out var m) && m.TryGetValue(Lang, out var s) ? s
        : Table.TryGetValue(key, out var m2) && m2.TryGetValue("en", out var e) ? e
        : key;

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["About"] = new() { ["da"]="Om", ["nl"]="Info", ["sv"]="Om", ["tr"]="Hakkında", ["ar"]="حول", ["ko"]="정보", ["en"]="About", ["de"]="Info", ["it"]="Informazioni", ["fr"]="À propos", ["pt"]="Sobre", ["es"]="Acerca de", ["zh"]="关于", ["ja"]="情報" },
        ["Th_System"] = new() { ["da"]="System", ["nl"]="Systeem", ["sv"]="System", ["tr"]="Sistem", ["ar"]="النظام", ["ko"]="시스템", ["en"]="System", ["de"]="System", ["it"]="Sistema", ["fr"]="Système", ["pt"]="Sistema", ["es"]="Sistema", ["zh"]="系统", ["ja"]="システム" },
        ["Th_Light"] = new() { ["da"]="Lys", ["nl"]="Licht", ["sv"]="Ljust", ["tr"]="Açık", ["ar"]="فاتح", ["ko"]="라이트", ["en"]="Light", ["de"]="Hell", ["it"]="Chiaro", ["fr"]="Clair", ["pt"]="Claro", ["es"]="Claro", ["zh"]="浅色", ["ja"]="ライト" },
        ["Th_Dark"] = new() { ["da"]="Mørk", ["nl"]="Donker", ["sv"]="Mörkt", ["tr"]="Koyu", ["ar"]="داكن", ["ko"]="다크", ["en"]="Dark", ["de"]="Dunkel", ["it"]="Scuro", ["fr"]="Sombre", ["pt"]="Escuro", ["es"]="Oscuro", ["zh"]="深色", ["ja"]="ダーク" },
        ["Details"] = new() { ["da"]="Tekniske detaljer", ["nl"]="Technische details", ["sv"]="Teknisk information", ["tr"]="Teknik ayrıntılar", ["ar"]="تفاصيل فنية", ["ko"]="기술 정보", ["en"]="Technical details", ["de"]="Technische Details", ["it"]="Dettagli tecnici", ["fr"]="Détails techniques", ["pt"]="Detalhes técnicos", ["es"]="Detalles técnicos", ["zh"]="技术细节", ["ja"]="技術詳細" },
        ["Grp_Installed"] = new() { ["da"]="Installeret på denne pc", ["nl"]="Geïnstalleerd op deze pc", ["sv"]="Installerade på den här datorn", ["tr"]="Bu bilgisayarda yüklü", ["ar"]="مثبتة على هذا الكمبيوتر", ["ko"]="이 PC에 설치됨", ["en"]="Installed on this PC", ["de"]="Auf diesem PC installiert", ["it"]="Installate su questo PC", ["fr"]="Installées sur ce PC", ["pt"]="Instaladas neste PC", ["es"]="Instaladas en este PC", ["zh"]="已在本机安装", ["ja"]="このPCにインストール済み" },
        ["Grp_Available"] = new() { ["da"]="Tilgængelige", ["nl"]="Beschikbaar", ["sv"]="Tillgängliga", ["tr"]="Kullanılabilir", ["ar"]="متاحة", ["ko"]="사용 가능", ["en"]="Available", ["de"]="Verfügbar", ["it"]="Disponibili", ["fr"]="Disponibles", ["pt"]="Disponíveis", ["es"]="Disponibles", ["zh"]="可用", ["ja"]="利用可能" },
        ["LoadFailed"] = new() { ["da"]="Kunne ikke indlæses: {0}", ["nl"]="Kan niet laden: {0}", ["sv"]="Kunde inte läsas in: {0}", ["tr"]="Yüklenemedi: {0}", ["ar"]="تعذر التحميل: {0}", ["ko"]="불러오지 못함: {0}", ["en"]="Could not load: {0}", ["de"]="Konnte nicht geladen werden: {0}", ["it"]="Impossibile caricare: {0}", ["fr"]="Chargement impossible : {0}", ["pt"]="Não foi possível carregar: {0}", ["es"]="No se pudo cargar: {0}", ["zh"]="无法加载：{0}", ["ja"]="読み込めませんでした：{0}" },
        ["AddServer"] = new() { ["da"]="Tilføj printserver…", ["nl"]="Printserver toevoegen…", ["sv"]="Lägg till skrivarserver…", ["tr"]="Yazıcı sunucusu ekle…", ["ar"]="إضافة خادم طباعة…", ["ko"]="프린트 서버 추가…", ["en"]="Add print server…", ["de"]="Druckserver hinzufügen…", ["it"]="Aggiungi server di stampa…", ["fr"]="Ajouter un serveur…", ["pt"]="Adicionar servidor…", ["es"]="Añadir servidor…", ["zh"]="添加打印服务器…", ["ja"]="プリントサーバーを追加…" },
        ["Theme"] = new() { ["da"]="Udseende", ["nl"]="Weergave", ["sv"]="Utseende", ["tr"]="Görünüm", ["ar"]="المظهر", ["ko"]="모양", ["en"]="Appearance", ["de"]="Darstellung", ["it"]="Aspetto", ["fr"]="Apparence", ["pt"]="Aparência", ["es"]="Apariencia", ["zh"]="外观", ["ja"]="外観" },
        ["Language"] = new() { ["da"]="Sprog", ["nl"]="Taal", ["sv"]="Språk", ["tr"]="Dil", ["ar"]="اللغة", ["ko"]="언어", ["en"]="Language", ["de"]="Sprache", ["it"]="Lingua", ["fr"]="Langue", ["pt"]="Idioma", ["es"]="Idioma", ["zh"]="语言", ["ja"]="言語" },
        ["ColIp"] = new() { ["da"]="IP", ["nl"]="IP", ["sv"]="IP", ["tr"]="IP", ["ar"]="IP", ["ko"]="IP", ["en"]="IP", ["de"]="IP", ["it"]="IP", ["fr"]="IP", ["pt"]="IP", ["es"]="IP", ["zh"]="IP", ["ja"]="IP" },
        // ---- printer status conditions ----
        ["St_Ready"] = new() { ["da"]="Klar", ["nl"]="Gereed", ["sv"]="Redo", ["tr"]="Hazır", ["ar"]="جاهزة", ["ko"]="준비됨", ["en"]="Ready", ["de"]="Bereit", ["it"]="Pronta", ["fr"]="Prête", ["pt"]="Pronta", ["es"]="Lista", ["zh"]="就绪", ["ja"]="準備完了" },
        ["St_PaperJam"] = new() { ["da"]="Papirstop", ["nl"]="Papierstoring", ["sv"]="Pappersstopp", ["tr"]="Kağıt sıkışması", ["ar"]="انحشار ورق", ["ko"]="용지 걸림", ["en"]="Paper jam", ["de"]="Papierstau", ["it"]="Inceppamento carta", ["fr"]="Bourrage papier", ["pt"]="Papel encravado", ["es"]="Atasco de papel", ["zh"]="卡纸", ["ja"]="紙詰まり" },
        ["St_PaperOut"] = new() { ["da"]="Ikke mere papir", ["nl"]="Papier op", ["sv"]="Slut på papper", ["tr"]="Kağıt bitti", ["ar"]="نفد الورق", ["ko"]="용지 없음", ["en"]="Out of paper", ["de"]="Kein Papier", ["it"]="Carta esaurita", ["fr"]="Plus de papier", ["pt"]="Sem papel", ["es"]="Sin papel", ["zh"]="缺纸", ["ja"]="用紙切れ" },
        ["St_PaperProblem"] = new() { ["en"]="Paper problem", ["de"]="Papierproblem", ["it"]="Problema carta", ["fr"]="Problème de papier", ["pt"]="Problema de papel", ["es"]="Problema de papel", ["zh"]="纸张问题", ["ja"]="用紙の問題" },
        ["St_TonerLow"] = new() { ["da"]="Toner lav", ["nl"]="Toner bijna op", ["sv"]="Toner låg", ["tr"]="Toner az", ["ar"]="الحبر منخفض", ["ko"]="토너 부족", ["en"]="Toner low", ["de"]="Toner niedrig", ["it"]="Toner in esaurimento", ["fr"]="Toner faible", ["pt"]="Toner baixo", ["es"]="Tóner bajo", ["zh"]="墨粉不足", ["ja"]="トナー残量低" },
        ["St_NoToner"] = new() { ["da"]="Toner tom", ["nl"]="Toner leeg", ["sv"]="Toner slut", ["tr"]="Toner bitti", ["ar"]="نفد الحبر", ["ko"]="토너 없음", ["en"]="Toner empty", ["de"]="Toner leer", ["it"]="Toner esaurito", ["fr"]="Toner vide", ["pt"]="Toner vazio", ["es"]="Tóner vacío", ["zh"]="墨粉用尽", ["ja"]="トナー切れ" },
        ["St_DoorOpen"] = new() { ["en"]="Cover open", ["de"]="Abdeckung offen", ["it"]="Sportello aperto", ["fr"]="Capot ouvert", ["pt"]="Tampa aberta", ["es"]="Tapa abierta", ["zh"]="盖板打开", ["ja"]="カバーが開いています" },
        ["St_BinFull"] = new() { ["en"]="Output tray full", ["de"]="Ausgabefach voll", ["it"]="Vassoio pieno", ["fr"]="Bac de sortie plein", ["pt"]="Bandeja cheia", ["es"]="Bandeja llena", ["zh"]="出纸盘已满", ["ja"]="排紙トレイ満杯" },
        ["St_UserAction"] = new() { ["en"]="Needs attention at the device", ["de"]="Eingriff am Gerät nötig", ["it"]="Intervento necessario", ["fr"]="Intervention requise", ["pt"]="Intervenção necessária", ["es"]="Requiere intervención", ["zh"]="需要在设备上处理", ["ja"]="本体での操作が必要" },
        ["St_OutOfMemory"] = new() { ["en"]="Out of memory", ["de"]="Speicher voll", ["it"]="Memoria esaurita", ["fr"]="Mémoire saturée", ["pt"]="Sem memória", ["es"]="Sin memoria", ["zh"]="内存不足", ["ja"]="メモリ不足" },
        ["St_Error"] = new() { ["da"]="Fejl", ["nl"]="Fout", ["sv"]="Fel", ["tr"]="Hata", ["ar"]="خطأ", ["ko"]="오류", ["en"]="Error", ["de"]="Fehler", ["it"]="Errore", ["fr"]="Erreur", ["pt"]="Erro", ["es"]="Error", ["zh"]="错误", ["ja"]="エラー" },
        ["St_Offline"] = new() { ["da"]="Offline", ["nl"]="Offline", ["sv"]="Offline", ["tr"]="Çevrimdışı", ["ar"]="غير متصلة", ["ko"]="오프라인", ["en"]="Offline", ["de"]="Offline", ["it"]="Offline", ["fr"]="Hors ligne", ["pt"]="Offline", ["es"]="Sin conexión", ["zh"]="脱机", ["ja"]="オフライン" },
        ["St_NotAvailable"] = new() { ["en"]="Not available", ["de"]="Nicht verfügbar", ["it"]="Non disponibile", ["fr"]="Non disponible", ["pt"]="Indisponível", ["es"]="No disponible", ["zh"]="不可用", ["ja"]="利用不可" },
        ["St_ServerUnknown"] = new() { ["en"]="Server status unknown", ["de"]="Serverstatus unbekannt", ["it"]="Stato server sconosciuto", ["fr"]="État du serveur inconnu", ["pt"]="Estado do servidor desconhecido", ["es"]="Estado del servidor desconocido", ["zh"]="服务器状态未知", ["ja"]="サーバー状態不明" },
        ["St_Paused"] = new() { ["da"]="Sat på pause", ["nl"]="Onderbroken", ["sv"]="Pausad", ["tr"]="Duraklatıldı", ["ar"]="متوقفة مؤقتًا", ["ko"]="일시 중지", ["en"]="Paused", ["de"]="Angehalten", ["it"]="In pausa", ["fr"]="En pause", ["pt"]="Pausada", ["es"]="En pausa", ["zh"]="已暂停", ["ja"]="一時停止" },
        ["St_PendingDeletion"] = new() { ["en"]="Being deleted", ["de"]="Wird gelöscht", ["it"]="In eliminazione", ["fr"]="Suppression en cours", ["pt"]="A ser eliminada", ["es"]="Eliminándose", ["zh"]="正在删除", ["ja"]="削除中" },
        ["St_ManualFeed"] = new() { ["en"]="Manual feed required", ["de"]="Manuelle Zufuhr nötig", ["it"]="Alimentazione manuale", ["fr"]="Alimentation manuelle", ["pt"]="Alimentação manual", ["es"]="Alimentación manual", ["zh"]="需手动送纸", ["ja"]="手差し給紙が必要" },
        ["St_PagePunt"] = new() { ["en"]="Page too complex", ["de"]="Seite zu komplex", ["it"]="Pagina troppo complessa", ["fr"]="Page trop complexe", ["pt"]="Página complexa demais", ["es"]="Página demasiado compleja", ["zh"]="页面过于复杂", ["ja"]="ページが複雑すぎます" },
        ["St_Printing"] = new() { ["da"]="Udskriver", ["nl"]="Bezig met afdrukken", ["sv"]="Skriver ut", ["tr"]="Yazdırıyor", ["ar"]="تطبع", ["ko"]="인쇄 중", ["en"]="Printing", ["de"]="Druckt", ["it"]="In stampa", ["fr"]="Impression", ["pt"]="A imprimir", ["es"]="Imprimiendo", ["zh"]="正在打印", ["ja"]="印刷中" },
        ["St_Processing"] = new() { ["en"]="Processing", ["de"]="Verarbeitet", ["it"]="Elaborazione", ["fr"]="Traitement", ["pt"]="A processar", ["es"]="Procesando", ["zh"]="处理中", ["ja"]="処理中" },
        ["St_WarmingUp"] = new() { ["en"]="Warming up", ["de"]="Aufwärmen", ["it"]="Riscaldamento", ["fr"]="Préchauffage", ["pt"]="A aquecer", ["es"]="Calentando", ["zh"]="预热中", ["ja"]="ウォームアップ中" },
        ["St_Initializing"] = new() { ["en"]="Initializing", ["de"]="Initialisiert", ["it"]="Inizializzazione", ["fr"]="Initialisation", ["pt"]="A inicializar", ["es"]="Inicializando", ["zh"]="初始化中", ["ja"]="初期化中" },
        ["St_Busy"] = new() { ["en"]="Busy", ["de"]="Beschäftigt", ["it"]="Occupata", ["fr"]="Occupée", ["pt"]="Ocupada", ["es"]="Ocupada", ["zh"]="忙", ["ja"]="ビジー" },
        ["St_Waiting"] = new() { ["en"]="Waiting", ["de"]="Wartet", ["it"]="In attesa", ["fr"]="En attente", ["pt"]="Em espera", ["es"]="Esperando", ["zh"]="等待中", ["ja"]="待機中" },
        ["St_IoActive"] = new() { ["en"]="Data transfer", ["de"]="Datenübertragung", ["it"]="Trasferimento dati", ["fr"]="Transfert de données", ["pt"]="Transferência de dados", ["es"]="Transferencia de datos", ["zh"]="数据传输中", ["ja"]="データ転送中" },
        ["St_PowerSave"] = new() { ["en"]="Power save", ["de"]="Energiesparmodus", ["it"]="Risparmio energetico", ["fr"]="Économie d'énergie", ["pt"]="Poupança de energia", ["es"]="Ahorro de energía", ["zh"]="节能模式", ["ja"]="省電力モード" },
        ["SetDefault"] = new() { ["da"]="Angiv som standardprinter", ["nl"]="Als standaardprinter instellen", ["sv"]="Ange som standardskrivare", ["tr"]="Varsayılan yazıcı yap", ["ar"]="تعيين كطابعة افتراضية", ["ko"]="기본 프린터로 설정", ["en"]="Set as default printer", ["de"]="Als Standarddrucker festlegen", ["it"]="Imposta come predefinita", ["fr"]="Définir comme imprimante par défaut", ["pt"]="Definir como impressora padrão", ["es"]="Establecer como predeterminada", ["zh"]="设为默认打印机", ["ja"]="既定のプリンターに設定" },
        ["IsDefault"] = new() { ["da"]="Standardprinter", ["nl"]="Standaardprinter", ["sv"]="Standardskrivare", ["tr"]="Varsayılan yazıcı", ["ar"]="الطابعة الافتراضية", ["ko"]="기본 프린터", ["en"]="Default printer", ["de"]="Standarddrucker", ["it"]="Stampante predefinita", ["fr"]="Imprimante par défaut", ["pt"]="Impressora padrão", ["es"]="Impresora predeterminada", ["zh"]="默认打印机", ["ja"]="既定のプリンター" },
        ["DeviceUp"] = new() { ["da"]="enheden svarer", ["nl"]="apparaat reageert", ["sv"]="enheten svarar", ["tr"]="cihaz yanıt veriyor", ["ar"]="الجهاز يستجيب", ["ko"]="장치 응답함", ["en"]="device responds", ["de"]="Gerät antwortet", ["it"]="il dispositivo risponde", ["fr"]="l'appareil répond", ["pt"]="o dispositivo responde", ["es"]="el dispositivo responde", ["zh"]="设备有响应", ["ja"]="機器が応答" },
        ["ProbeHint"] = new() { ["en"]="Checked live from this PC on ports 9100/631/515/80. The server's status can be out of date.", ["de"]="Live von diesem PC über Ports 9100/631/515/80 geprüft. Der Serverstatus kann veraltet sein.", ["it"]="Verificato in tempo reale da questo PC sulle porte 9100/631/515/80. Lo stato del server può essere obsoleto.", ["fr"]="Vérifié en direct depuis ce PC sur les ports 9100/631/515/80. L'état du serveur peut être obsolète.", ["pt"]="Verificado em tempo real deste PC nas portas 9100/631/515/80. O estado do servidor pode estar desatualizado.", ["es"]="Comprobado en vivo desde este PC en los puertos 9100/631/515/80. El estado del servidor puede estar desactualizado.", ["zh"]="从本机通过端口 9100/631/515/80 实时检测。服务器状态可能已过期。", ["ja"]="このPCからポート9100/631/515/80で即時確認。サーバーの状態は古い場合があります。" },
        ["InstallFirst"] = new() { ["da"]="Installer printeren først, og angiv den derefter som standard.", ["nl"]="Installeer de printer eerst en stel deze daarna in als standaard.", ["sv"]="Installera skrivaren först och ange den sedan som standard.", ["tr"]="Önce yazıcıyı yükleyin, sonra varsayılan yapın.", ["ar"]="ثبّت الطابعة أولاً ثم عيّنها كافتراضية.", ["ko"]="프린터를 먼저 설치한 후 기본으로 설정하세요.", ["en"]="Install the printer first, then set it as default.", ["de"]="Drucker zuerst installieren, dann als Standard festlegen.", ["it"]="Installa prima la stampante, poi impostala come predefinita.", ["fr"]="Installez d'abord l'imprimante, puis définissez-la par défaut.", ["pt"]="Instale a impressora primeiro e depois defina como padrão.", ["es"]="Instale la impresora primero y luego establézcala como predeterminada.", ["zh"]="请先安装打印机，然后设为默认。", ["ja"]="先にプリンターをインストールしてから既定に設定してください。" },
        ["Default"] = new() { ["da"]="Standard", ["nl"]="Standaard", ["sv"]="Standard", ["tr"]="Varsayılan", ["ar"]="افتراضي", ["ko"]="기본", ["en"]="Default", ["de"]="Standard", ["it"]="Predefinita", ["fr"]="Défaut", ["pt"]="Padrão", ["es"]="Predet.", ["zh"]="默认", ["ja"]="既定" },
        ["Copied"] = new() { ["da"]="Kopieret: {0}", ["nl"]="Gekopieerd: {0}", ["sv"]="Kopierat: {0}", ["tr"]="Kopyalandı: {0}", ["ar"]="تم النسخ: {0}", ["ko"]="복사됨: {0}", ["en"]="Copied: {0}", ["de"]="Kopiert: {0}", ["it"]="Copiato: {0}", ["fr"]="Copié : {0}", ["pt"]="Copiado: {0}", ["es"]="Copiado: {0}", ["zh"]="已复制：{0}", ["ja"]="コピーしました：{0}" },
        ["AddDevice"] = new() { ["da"]="Tilføj enhed", ["nl"]="Apparaat toevoegen", ["sv"]="Lägg till enhet", ["tr"]="Cihaz ekle", ["ar"]="إضافة جهاز", ["ko"]="장치 추가", ["en"]="Add device", ["de"]="Gerät hinzufügen", ["it"]="Aggiungi dispositivo", ["fr"]="Ajouter un appareil", ["pt"]="Adicionar dispositivo", ["es"]="Agregar dispositivo", ["zh"]="添加设备", ["ja"]="デバイスの追加" },
        ["ReleaseNotes"] = new() { ["da"]="Udgivelsesnoter", ["nl"]="Releaseopmerkingen", ["sv"]="Versionsinformation", ["tr"]="Sürüm notları", ["ar"]="ملاحظات الإصدار", ["ko"]="릴리스 노트", ["en"]="Release notes", ["de"]="Versionshinweise", ["it"]="Note di rilascio", ["fr"]="Notes de version", ["pt"]="Notas de versão", ["es"]="Notas de la versión", ["zh"]="版本说明", ["ja"]="リリースノート" },
        ["Refresh"] = new() { ["en"]="Refresh", ["de"]="Aktualisieren", ["it"]="Aggiorna", ["fr"]="Actualiser", ["pt"]="Atualizar", ["es"]="Actualizar", ["zh"]="刷新", ["ja"]="更新", ["da"]="Opdater", ["nl"]="Vernieuwen", ["sv"]="Uppdatera", ["tr"]="Yenile", ["ar"]="تحديث", ["ko"]="새로 고침" },
        ["TestPage"] = new() { ["en"]="Print test page", ["de"]="Testseite drucken", ["it"]="Stampa pagina di prova", ["fr"]="Imprimer une page de test", ["pt"]="Imprimir página de teste", ["es"]="Imprimir página de prueba", ["zh"]="打印测试页", ["ja"]="テストページを印刷", ["da"]="Udskriv testside", ["nl"]="Testpagina afdrukken", ["sv"]="Skriv ut testsida", ["tr"]="Test sayfası yazdır", ["ar"]="طباعة صفحة اختبار", ["ko"]="테스트 페이지 인쇄" },
        ["TestSent"] = new() { ["en"]="Test page sent to {0}", ["de"]="Testseite an {0} gesendet", ["it"]="Pagina di prova inviata a {0}", ["fr"]="Page de test envoyée à {0}", ["pt"]="Página de teste enviada para {0}", ["es"]="Página de prueba enviada a {0}", ["zh"]="测试页已发送至 {0}", ["ja"]="{0} にテストページを送信しました", ["da"]="Testside sendt til {0}", ["nl"]="Testpagina verzonden naar {0}", ["sv"]="Testsida skickad till {0}", ["tr"]="Test sayfası {0} yazıcısına gönderildi", ["ar"]="أُرسلت صفحة الاختبار إلى {0}", ["ko"]="{0}(으)로 테스트 페이지를 보냈습니다" },
        ["Export"] = new() { ["en"]="Export to Excel", ["de"]="Nach Excel exportieren", ["it"]="Esporta in Excel", ["fr"]="Exporter vers Excel", ["pt"]="Exportar para Excel", ["es"]="Exportar a Excel", ["zh"]="导出到 Excel", ["ja"]="Excel にエクスポート", ["da"]="Eksportér til Excel", ["nl"]="Exporteren naar Excel", ["sv"]="Exportera till Excel", ["tr"]="Excel'e aktar", ["ar"]="تصدير إلى Excel", ["ko"]="Excel로 내보내기" },
        ["ExportShort"] = new() { ["en"]="Export", ["de"]="Exportieren", ["it"]="Esporta", ["fr"]="Exporter", ["pt"]="Exportar", ["es"]="Exportar", ["zh"]="导出", ["ja"]="エクスポート", ["da"]="Eksportér", ["nl"]="Exporteren", ["sv"]="Exportera", ["tr"]="Dışa aktar", ["ar"]="تصدير", ["ko"]="내보내기" },
        ["ExportDone"] = new() { ["en"]="Export complete", ["de"]="Export abgeschlossen", ["it"]="Esportazione completata", ["fr"]="Exportation terminée", ["pt"]="Exportação concluída", ["es"]="Exportación completada", ["zh"]="导出完成", ["ja"]="エクスポートが完了しました", ["da"]="Eksport fuldført", ["nl"]="Export voltooid", ["sv"]="Export klar", ["tr"]="Dışa aktarma tamamlandı", ["ar"]="اكتمل التصدير", ["ko"]="내보내기 완료"},
        ["Open"] = new() { ["en"]="Open", ["de"]="Öffnen", ["it"]="Apri", ["fr"]="Ouvrir", ["pt"]="Abrir", ["es"]="Abrir", ["zh"]="打开", ["ja"]="開く", ["da"]="Åbn", ["nl"]="Openen", ["sv"]="Öppna", ["tr"]="Aç", ["ar"]="فتح", ["ko"]="열기" },
        ["Close"] = new() { ["en"]="Close", ["de"]="Schließen", ["it"]="Chiudi", ["fr"]="Fermer", ["pt"]="Fechar", ["es"]="Cerrar", ["zh"]="关闭", ["ja"]="閉じる", ["da"]="Luk", ["nl"]="Sluiten", ["sv"]="Stäng", ["tr"]="Kapat", ["ar"]="إغلاق", ["ko"]="닫기" },
        ["Signing"] = new() { ["en"]="Code signing", ["de"]="Codesignierung", ["it"]="Firma del codice", ["fr"]="Signature du code", ["pt"]="Assinatura de código", ["es"]="Firma de código", ["zh"]="代码签名", ["ja"]="コード署名", ["da"]="Kodesignering", ["nl"]="Code-ondertekening", ["sv"]="Kodsignering", ["tr"]="Kod imzalama", ["ar"]="توقيع التعليمات البرمجية", ["ko"]="코드 서명" },
        ["SigningText"] = new() { ["en"]="Releases are unsigned. Before rollout, sign this exe with your company certificate — one command with deploy/sign.ps1 from the repository. Signed builds pass SmartScreen and can be trusted by publisher in your security tools.", ["de"]="Releases sind unsigniert. Vor dem Rollout die EXE mit dem Firmenzertifikat signieren — ein Befehl mit deploy/sign.ps1 aus dem Repository. Signierte Versionen passieren SmartScreen und können in den Sicherheitstools per Herausgeber freigegeben werden." },
        ["DriverType"] = new() { ["en"]="Driver type", ["de"]="Treibertyp", ["it"]="Tipo di driver", ["fr"]="Type de pilote", ["pt"]="Tipo de driver", ["es"]="Tipo de controlador", ["zh"]="驱动类型", ["ja"]="ドライバーの種類", ["da"]="Drivertype", ["nl"]="Stuurprogrammatype", ["sv"]="Drivrutinstyp", ["tr"]="Sürücü türü", ["ar"]="نوع برنامج التشغيل", ["ko"]="드라이버 유형" },
        ["Type4Tip"] = new() { ["en"]="Type 4 driver: installs without admin prompts and is ready for Windows Protected Print.", ["de"]="Typ-4-Treiber: Installation ohne Admin-Abfrage, bereit für Windows Protected Print." },
        ["Type3Tip"] = new() { ["en"]="Type 3 driver: may trigger admin credential prompts on install (KB5005652). Consider a Type 4 driver on the server.", ["de"]="Typ-3-Treiber: kann bei der Installation eine Admin-Abfrage auslösen (KB5005652). Auf dem Server möglichst einen Typ-4-Treiber verwenden." },
        ["AlignLeft"] = new() { ["en"]="Left", ["de"]="Links", ["it"]="Sinistra", ["fr"]="Gauche", ["pt"]="Esquerda", ["es"]="Izquierda", ["zh"]="左对齐", ["ja"]="左揃え", ["da"]="Venstre", ["nl"]="Links", ["sv"]="Vänster", ["tr"]="Sol", ["ar"]="يسار", ["ko"]="왼쪽" },
        ["AlignCenter"] = new() { ["en"]="Center", ["de"]="Zentriert", ["it"]="Centro", ["fr"]="Centré", ["pt"]="Centro", ["es"]="Centrado", ["zh"]="居中", ["ja"]="中央揃え", ["da"]="Centreret", ["nl"]="Gecentreerd", ["sv"]="Centrerad", ["tr"]="Orta", ["ar"]="وسط", ["ko"]="가운데" },
        ["ClearQueue"] = new() { ["en"]="Clear print queue", ["de"]="Druckwarteschlange leeren", ["it"]="Svuota coda di stampa", ["fr"]="Vider la file d'impression", ["pt"]="Limpar fila de impressão", ["es"]="Vaciar cola de impresión", ["zh"]="清空打印队列", ["ja"]="印刷キューをクリア", ["da"]="Ryd udskriftskø", ["nl"]="Wachtrij leegmaken", ["sv"]="Rensa utskriftskön", ["tr"]="Yazdırma kuyruğunu temizle", ["ar"]="مسح قائمة انتظار الطباعة", ["ko"]="인쇄 대기열 지우기" },
        ["ClearedJobs"] = new() { ["en"]="{0} job(s) removed — {1}", ["de"]="{0} Auftrag/Aufträge entfernt — {1}", ["it"]="{0} lavori rimossi — {1}", ["fr"]="{0} travaux supprimés — {1}", ["pt"]="{0} trabalhos removidos — {1}", ["es"]="{0} trabajos eliminados — {1}", ["zh"]="已移除 {0} 个作业 — {1}", ["ja"]="{0} 件のジョブを削除 — {1}", ["da"]="{0} job fjernet — {1}", ["nl"]="{0} taken verwijderd — {1}", ["sv"]="{0} jobb borttagna — {1}", ["tr"]="{0} iş kaldırıldı — {1}", ["ar"]="تمت إزالة {0} مهمة — {1}", ["ko"]="작업 {0}개 제거됨 — {1}" },
        ["ThisPC"] = new() { ["da"]="Denne pc", ["nl"]="Deze pc", ["sv"]="Den här datorn", ["tr"]="Bu bilgisayar", ["ar"]="هذا الكمبيوتر", ["ko"]="이 PC", ["en"]="This PC", ["de"]="Dieser PC", ["it"]="Questo PC", ["fr"]="Ce PC", ["pt"]="Este PC", ["es"]="Este PC", ["zh"]="此电脑", ["ja"]="このPC" },
        ["Columns"] = new() { ["da"]="Kolonner", ["nl"]="Kolommen", ["sv"]="Kolumner", ["tr"]="Sütunlar", ["ar"]="الأعمدة", ["ko"]="열", ["en"]="Columns", ["de"]="Spalten", ["it"]="Colonne", ["fr"]="Colonnes", ["pt"]="Colunas", ["es"]="Columnas", ["zh"]="列", ["ja"]="列" },
        ["ColJobs"] = new() { ["da"]="Job", ["nl"]="Taken", ["sv"]="Jobb", ["tr"]="İşler", ["ar"]="المهام", ["ko"]="작업", ["en"]="Jobs", ["de"]="Aufträge", ["it"]="Lavori", ["fr"]="Travaux", ["pt"]="Trabalhos", ["es"]="Trabajos", ["zh"]="作业", ["ja"]="ジョブ" },
        ["ColModel"] = new() { ["da"]="Model", ["nl"]="Model", ["sv"]="Modell", ["tr"]="Model", ["ar"]="الطراز", ["ko"]="모델", ["en"]="Model", ["de"]="Modell", ["it"]="Modello", ["fr"]="Modèle", ["pt"]="Modelo", ["es"]="Modelo", ["zh"]="型号", ["ja"]="機種" },
        ["ColSerial"] = new() { ["da"]="Serienr.", ["nl"]="Serienr.", ["sv"]="Serienr", ["tr"]="Seri no", ["ar"]="الرقم التسلسلي", ["ko"]="일련번호", ["en"]="Serial", ["de"]="Seriennr.", ["it"]="Seriale", ["fr"]="N° de série", ["pt"]="Série", ["es"]="N.º de serie", ["zh"]="序列号", ["ja"]="シリアル" },
        ["ColPages"] = new() { ["da"]="Sider", ["nl"]="Pagina's", ["sv"]="Sidor", ["tr"]="Sayfa", ["ar"]="الصفحات", ["ko"]="페이지", ["en"]="Pages", ["de"]="Seiten", ["it"]="Pagine", ["fr"]="Pages", ["pt"]="Páginas", ["es"]="Páginas", ["zh"]="页数", ["ja"]="印刷枚数" },
        ["ColUptime"] = new() { ["da"]="Oppetid", ["nl"]="Uptime", ["sv"]="Drifttid", ["tr"]="Çalışma süresi", ["ar"]="مدة التشغيل", ["ko"]="가동 시간", ["en"]="Uptime", ["de"]="Laufzeit", ["it"]="Attività", ["fr"]="Durée active", ["pt"]="Tempo ativo", ["es"]="Tiempo activo", ["zh"]="运行时间", ["ja"]="稼働時間" },
        ["ColTrays"] = new() { ["da"]="Papir", ["nl"]="Papier", ["sv"]="Papper", ["tr"]="Kağıt", ["ar"]="الورق", ["ko"]="용지", ["en"]="Paper", ["de"]="Papier", ["it"]="Carta", ["fr"]="Papier", ["pt"]="Papel", ["es"]="Papel", ["zh"]="纸张", ["ja"]="用紙" },
        ["ColDisplay"] = new() { ["da"]="Display", ["nl"]="Display", ["sv"]="Display", ["tr"]="Ekran", ["ar"]="الشاشة", ["ko"]="디스플레이", ["en"]="Display", ["de"]="Anzeige", ["it"]="Display", ["fr"]="Écran", ["pt"]="Visor", ["es"]="Pantalla", ["zh"]="面板信息", ["ja"]="パネル表示" },
        ["ColDriver"] = new() { ["da"]="Driver", ["nl"]="Stuurprogramma", ["sv"]="Drivrutin", ["tr"]="Sürücü", ["ar"]="برنامج التشغيل", ["ko"]="드라이버", ["en"]="Driver", ["de"]="Treiber", ["it"]="Driver", ["fr"]="Pilote", ["pt"]="Controlador", ["es"]="Controlador", ["zh"]="驱动程序", ["ja"]="ドライバー" },
        ["Server"] = new() { ["da"]="Printserver", ["nl"]="Printserver", ["sv"]="Skrivarserver", ["tr"]="Yazıcı sunucusu", ["ar"]="خادم الطباعة", ["ko"]="프린트 서버", ["en"]="Print server", ["de"]="Druckserver", ["it"]="Server di stampa", ["fr"]="Serveur d'impression", ["pt"]="Servidor de impressão", ["es"]="Servidor de impresión", ["zh"]="打印服务器", ["ja"]="プリントサーバー" },
        ["Load"] = new() { ["da"]="Indlæs", ["nl"]="Laden", ["sv"]="Läs in", ["tr"]="Yükle", ["ar"]="تحميل", ["ko"]="불러오기", ["en"]="Load", ["de"]="Laden", ["it"]="Carica", ["fr"]="Charger", ["pt"]="Carregar", ["es"]="Cargar", ["zh"]="加载", ["ja"]="読み込み" },
        ["Search"] = new() { ["da"]="Søg efter printere…", ["nl"]="Printers zoeken…", ["sv"]="Sök skrivare…", ["tr"]="Yazıcı ara…", ["ar"]="البحث عن طابعات…", ["ko"]="프린터 검색…", ["en"]="Search printers…", ["de"]="Drucker suchen…", ["it"]="Cerca stampanti…", ["fr"]="Rechercher…", ["pt"]="Pesquisar…", ["es"]="Buscar…", ["zh"]="搜索打印机…", ["ja"]="プリンターを検索…" },
        ["ColPrinter"] = new() { ["da"]="Printer", ["nl"]="Printer", ["sv"]="Skrivare", ["tr"]="Yazıcı", ["ar"]="الطابعة", ["ko"]="프린터", ["en"]="Printer", ["de"]="Drucker", ["it"]="Stampante", ["fr"]="Imprimante", ["pt"]="Impressora", ["es"]="Impresora", ["zh"]="打印机", ["ja"]="プリンター" },
        ["ColLocation"] = new() { ["da"]="Placering", ["nl"]="Locatie", ["sv"]="Plats", ["tr"]="Konum", ["ar"]="الموقع", ["ko"]="위치", ["en"]="Location", ["de"]="Standort", ["it"]="Posizione", ["fr"]="Emplacement", ["pt"]="Localização", ["es"]="Ubicación", ["zh"]="位置", ["ja"]="設置場所" },
        ["ColStatus"] = new() { ["da"]="Status", ["nl"]="Status", ["sv"]="Status", ["tr"]="Durum", ["ar"]="الحالة", ["ko"]="상태", ["en"]="Status", ["de"]="Status", ["it"]="Stato", ["fr"]="État", ["pt"]="Estado", ["es"]="Estado", ["zh"]="状态", ["ja"]="状態" },
        ["ColToner"] = new() { ["da"]="Toner", ["nl"]="Toner", ["sv"]="Toner", ["tr"]="Toner", ["ar"]="الحبر", ["ko"]="토너", ["en"]="Toner", ["de"]="Toner", ["it"]="Toner", ["fr"]="Toner", ["pt"]="Toner", ["es"]="Tóner", ["zh"]="墨粉", ["ja"]="トナー" },
        ["ColAction"] = new() { ["da"]="Installeret", ["nl"]="Geïnstalleerd", ["sv"]="Installerad", ["tr"]="Yüklü", ["ar"]="مثبتة", ["ko"]="설치됨", ["en"]="Installed", ["de"]="Installiert", ["it"]="Installata", ["fr"]="Installée", ["pt"]="Instalada", ["es"]="Instalada", ["zh"]="已安装", ["ja"]="インストール済み" },
        ["Install"] = new() { ["da"]="Installer", ["nl"]="Installeren", ["sv"]="Installera", ["tr"]="Yükle", ["ar"]="تثبيت", ["ko"]="설치", ["en"]="Install", ["de"]="Installieren", ["it"]="Installa", ["fr"]="Installer", ["pt"]="Instalar", ["es"]="Instalar", ["zh"]="安装", ["ja"]="インストール" },
        ["Remove"] = new() { ["da"]="Fjern", ["nl"]="Verwijderen", ["sv"]="Ta bort", ["tr"]="Kaldır", ["ar"]="إزالة", ["ko"]="제거", ["en"]="Remove", ["de"]="Entfernen", ["it"]="Rimuovi", ["fr"]="Retirer", ["pt"]="Remover", ["es"]="Quitar", ["zh"]="移除", ["ja"]="削除" },
        ["Installing"] = new() { ["da"]="Installerer…", ["nl"]="Installeren…", ["sv"]="Installerar…", ["tr"]="Yükleniyor…", ["ar"]="جارٍ التثبيت…", ["ko"]="설치 중…", ["en"]="Installing…", ["de"]="Wird installiert…", ["it"]="Installazione…", ["fr"]="Installation…", ["pt"]="Instalando…", ["es"]="Instalando…", ["zh"]="正在安装…", ["ja"]="インストール中…" },
        ["Removing"] = new() { ["da"]="Fjerner…", ["nl"]="Verwijderen…", ["sv"]="Tar bort…", ["tr"]="Kaldırılıyor…", ["ar"]="جارٍ الإزالة…", ["ko"]="제거 중…", ["en"]="Removing…", ["de"]="Wird entfernt…", ["it"]="Rimozione…", ["fr"]="Suppression…", ["pt"]="Removendo…", ["es"]="Quitando…", ["zh"]="正在移除…", ["ja"]="削除中…" },
        ["ConfirmRemove"] = new() { ["da"]="Fjern forbindelsen til \"{0}\"?", ["nl"]="Verbinding met \"{0}\" verwijderen?", ["sv"]="Ta bort anslutningen till \"{0}\"?", ["tr"]="\"{0}\" bağlantısı kaldırılsın mı?", ["ar"]="إزالة الاتصال بـ \"{0}\"؟", ["ko"]="\"{0}\" 연결을 제거할까요?", ["en"]="Remove the connection to \"{0}\"?", ["de"]="Verbindung zu „{0}“ entfernen?", ["it"]="Rimuovere la connessione a \"{0}\"?", ["fr"]="Retirer la connexion à « {0} » ?", ["pt"]="Remover a conexão com \"{0}\"?", ["es"]="¿Quitar la conexión a \"{0}\"?", ["zh"]="移除与“{0}”的连接？", ["ja"]="「{0}」への接続を削除しますか？" },
        ["CountLoaded"] = new() { ["da"]="{0} printere · {1} installeret", ["nl"]="{0} printers · {1} geïnstalleerd", ["sv"]="{0} skrivare · {1} installerade", ["tr"]="{0} yazıcı · {1} yüklü", ["ar"]="{0} طابعة · {1} مثبتة", ["ko"]="{0}대 · 설치됨 {1}대", ["en"]="{0} printers · {1} installed", ["de"]="{0} Drucker · {1} installiert", ["it"]="{0} stampanti · {1} installate", ["fr"]="{0} imprimantes · {1} installées", ["pt"]="{0} impressoras · {1} instaladas", ["es"]="{0} impresoras · {1} instaladas", ["zh"]="{0} 台打印机 · 已安装 {1} 台", ["ja"]="{0} 台 · インストール済み {1} 台" },
        ["Filtered"] = new() { ["da"]="{0} af {1} vist", ["nl"]="{0} van {1} getoond", ["sv"]="{0} av {1} visas", ["tr"]="{0}/{1} gösteriliyor", ["ar"]="عرض {0} من {1}", ["ko"]="{0}/{1} 표시", ["en"]="{0} of {1} shown", ["de"]="{0} von {1} angezeigt", ["it"]="{0} di {1} mostrate", ["fr"]="{0} sur {1} affichées", ["pt"]="{0} de {1} exibidas", ["es"]="{0} de {1} mostradas", ["zh"]="显示 {0}/{1}", ["ja"]="{0}/{1} 件を表示" },
        // Status values
        // Error explanations
        ["Err_Rpc"] = new() { ["en"]="Connection blocked (0x0000011b): the firewall is blocking print RPC traffic, or RPC encryption settings differ between this PC and the server. Please contact IT.", ["de"]="Verbindung blockiert (0x0000011b): Die Firewall blockiert den Druck-RPC-Verkehr oder die RPC-Verschlüsselung stimmt zwischen PC und Server nicht überein. Bitte IT kontaktieren.", ["it"]="Connessione bloccata (0x0000011b): il firewall blocca il traffico RPC di stampa o le impostazioni di crittografia RPC non coincidono. Contattare l'IT.", ["fr"]="Connexion bloquée (0x0000011b) : le pare-feu bloque le trafic RPC d'impression ou les paramètres de chiffrement RPC diffèrent. Contactez le service informatique.", ["pt"]="Conexão bloqueada (0x0000011b): o firewall bloqueia o tráfego RPC de impressão ou as configurações de criptografia RPC divergem. Contacte a TI.", ["es"]="Conexión bloqueada (0x0000011b): el firewall bloquea el tráfico RPC de impresión o la configuración de cifrado RPC no coincide. Contacte con TI.", ["zh"]="连接被阻止 (0x0000011b)：防火墙阻止了打印 RPC 流量，或本机与服务器的 RPC 加密设置不一致。请联系 IT。", ["ja"]="接続がブロックされました (0x0000011b)：ファイアウォールが印刷RPC通信を遮断しているか、RPC暗号化設定が一致していません。IT部門にお問い合わせください。" },
        ["Err_AccessDenied"] = new() { ["en"]="Access denied: your organization's Point-and-Print policy does not allow installing this driver without administrator rights. Please contact IT.", ["de"]="Zugriff verweigert: Die Point-and-Print-Richtlinie Ihrer Organisation erlaubt die Treiberinstallation ohne Administratorrechte nicht. Bitte IT kontaktieren.", ["it"]="Accesso negato: i criteri Point-and-Print non consentono di installare questo driver senza diritti di amministratore. Contattare l'IT.", ["fr"]="Accès refusé : la stratégie Point-and-Print n'autorise pas l'installation de ce pilote sans droits d'administrateur. Contactez le service informatique.", ["pt"]="Acesso negado: a política Point-and-Print não permite instalar este driver sem direitos de administrador. Contacte a TI.", ["es"]="Acceso denegado: la política Point-and-Print no permite instalar este controlador sin derechos de administrador. Contacte con TI.", ["zh"]="访问被拒绝：组织的 Point-and-Print 策略不允许在无管理员权限的情况下安装此驱动程序。请联系 IT。", ["ja"]="アクセス拒否：組織のPoint-and-Printポリシーにより、管理者権限なしでこのドライバーをインストールできません。IT部門にお問い合わせください。" },
        ["Err_Driver"] = new() { ["en"]="No suitable driver for this PC is available on the server. Please contact IT.", ["de"]="Auf dem Server ist kein passender Treiber für diesen PC verfügbar. Bitte IT kontaktieren.", ["it"]="Nessun driver adatto disponibile sul server per questo PC. Contattare l'IT.", ["fr"]="Aucun pilote adapté à ce PC n'est disponible sur le serveur. Contactez le service informatique.", ["pt"]="Não há driver adequado para este PC no servidor. Contacte a TI.", ["es"]="No hay un controlador adecuado para este PC en el servidor. Contacte con TI.", ["zh"]="服务器上没有适用于此电脑的驱动程序。请联系 IT。", ["ja"]="このPCに適したドライバーがサーバーにありません。IT部門にお問い合わせください。" },
        ["Err_ServerDown"] = new() { ["en"]="The print server cannot be reached. Check the server name and your network connection.", ["de"]="Der Druckserver ist nicht erreichbar. Servernamen und Netzwerkverbindung prüfen.", ["it"]="Il server di stampa non è raggiungibile. Verificare il nome del server e la rete.", ["fr"]="Le serveur d'impression est injoignable. Vérifiez le nom du serveur et le réseau.", ["pt"]="O servidor de impressão está inacessível. Verifique o nome do servidor e a rede.", ["es"]="No se puede acceder al servidor de impresión. Compruebe el nombre del servidor y la red.", ["zh"]="无法访问打印服务器。请检查服务器名称和网络连接。", ["ja"]="プリントサーバーに接続できません。サーバー名とネットワーク接続を確認してください。" },
        ["Err_NotFound"] = new() { ["en"]="Printer or server not found.", ["de"]="Drucker oder Server nicht gefunden.", ["it"]="Stampante o server non trovati.", ["fr"]="Imprimante ou serveur introuvable.", ["pt"]="Impressora ou servidor não encontrado.", ["es"]="Impresora o servidor no encontrado.", ["zh"]="未找到打印机或服务器。", ["ja"]="プリンターまたはサーバーが見つかりません。" },
        ["Err_Generic"] = new() { ["en"]="The operation failed (error {0}).", ["de"]="Der Vorgang ist fehlgeschlagen (Fehler {0}).", ["it"]="Operazione non riuscita (errore {0}).", ["fr"]="L'opération a échoué (erreur {0}).", ["pt"]="A operação falhou (erro {0}).", ["es"]="La operación falló (error {0}).", ["zh"]="操作失败（错误 {0}）。", ["ja"]="操作に失敗しました（エラー {0}）。" },
    };
}
